FROM s2e/viper_depends
MAINTAINER Seamus Tuohy <code@seamustuohy.com>

# Will force rebuild from this point based on the date
# See installer for info
ARG GIT_CACHE_DATE="2018-08-26-09"

## TO USE LOCAL CODEBASE
WORKDIR /home/viper
COPY code/viper viper
RUN sudo chown -R viper:viper viper

WORKDIR /home/viper
RUN cd viper \
    && git submodule init \
    && git submodule update

WORKDIR /home/viper/viper
RUN sudo -H pip3 install .
